apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-monitor-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: flask-monitor
  template:
    metadata:
      labels:
        app: flask-monitor
    spec:
      containers:
        - name: flask-monitor
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5001
          env:
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.aws_access_key | quote }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.aws_secret_key | quote }}