apiVersion: v1
kind: Service
metadata:
  name: devops-flask-svc
spec:
  type: ClusterIP
  selector:
    app: devops-flask-app
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}